const Menu = [
    {
        id: 1,
        image: `${process.env.PUBLIC_URL}/images/break1.jpg`,
        name: 'bread',
        category: 'breakfast',
        price: '220 tk',
        description: ' Lorem ipsum dolor, sit amet cons klr adipi sicin',
    },
    {
        id: 2,
        image: `${process.env.PUBLIC_URL}/images/break2.jpg`,
        name: 'cake',
        category: 'breakfast',
        price: '250 tk',
        description: ' Lorem ipsum dolor, sit amet cons klr adipi sicin',
    },
    {
        id: 3,
        image: `${process.env.PUBLIC_URL}/images/break3.jpg`,
        name: 'Rice',
        category: 'breakfast',
        price: '200 tk',
        description: ' Lorem ipsum dolor, sit amet cons klr adipi sicin',
    },
    {
        id: 4,
        image: `${process.env.PUBLIC_URL}/images/break4.jpg`,
        name: 'Toast',
        category: 'breakfast',
        price: '180 tk',
        description: 'Lorem ipsum dolor, sit amet cons klr adipi sicin',
    },
    {
        id: 5,
        image: `${process.env.PUBLIC_URL}/images/lunch1.jpg`,
        name: 'Steak',
        category: 'lunch',
        price: '500 tk',
        description: ' Lorem ipsum dolor, sit amet cons klr adipi sicin',
    },
    {
        id: 6,
        image: `${process.env.PUBLIC_URL}/images/lunch2.jpg`,
        name: 'Fish',
        category: 'lunch',
        price: '320 tk',
        description: ' Lorem ipsum dolor, sit amet cons klr adipi sicin',
    },
    {
        id: 7,
        image: `${process.env.PUBLIC_URL}/images/lunch3.jpg`,
        name: 'Curry',
        category: 'lunch',
        price: '420 tk',
        description: ' Lorem ipsum dolor, sit amet cons klr adipi sicin',
    },
    {
        id: 8,
        image: `${process.env.PUBLIC_URL}/images/dinner1.jpg`,
        name: 'meat',
        category: 'dinner',
        price: '330 tk',
        description: ' Lorem ipsum dolor, sit amet cons klr adipi sicin',
    },
    {
        id: 9,
        image: `${process.env.PUBLIC_URL}/images/dinner2.jpg`,
        name: 'Nodles',
        category: 'dinner',
        price: '720 tk',
        description: ' Lorem ipsum dolor, sit amet cons klr adipi sicin',
    },
    {
        id: 10,
        image: `${process.env.PUBLIC_URL}/images/dinner3.jpg`,
        name: 'Burger',
        category: 'dinner',
        price: '455 tk',
        description: ' Lorem ipsum dolor, sit amet cons klr adipi sicin',
    },
];
export default Menu;
